### ISSUE TITLE
Make elements deletable

### ISSUE THREAD

**Issue by LynxUtz** [msawired/OPC#3]
Add this fonction : 
```js
//  VariableName store the value of the element, like a toggle element …
OPC.delete(VariableName)
// Or : 
VariableName.delete();
```

**Comment by LynxUtz** [comment]
Where is the code who’s respond to window message OPC are sending ?

**Comment by msawired** [comment]
Hello @LynxUtz, Yes delete function makes sense. I will look into it. 

This library is meant to be agnostic of the interface part: Anyone can develop a UI for the responding messages. The UI on OpenProcessing is highly integrated to its own UI therefore not included here, but I guess a basic examples can be added to test the library in general.

**Comment by LynxUtz** [comment]
Thanks.

**Comment by LynxUtz** [comment]
I asked this last question because I didn't understand the uses of URL() function and 
the postMessage() function. 

Otherwise, I would have proposed something

**Comment by msawired** [comment]
Yes, these could be better documented I guess. URL function allows you to provide initial values in the URL parameters instead of the defaults used in the functions. For example, you can provide https://www.yourwebsite.com/?name=test&level=4 to set the initial OPC parameters name to "test" and level to "4". 
PostMessage is used to communicate the parameters with the parent (or sibling) window, where the UI should be displayed. In the case of OpenProcessing, it sends the parameters to the main OpenProcessing sketch page.

**Comment by msawired** [comment]
Hey @LynxUtz, I added the OPC.delete() function. You can use it to remove variables now.

**Comment by LynxUtz** [comment]
Thank you.
